name: Run Scraper Daily

on:
  schedule:
    - cron: '0 15 * * *'  # This cron schedule is in UTC time
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run scraper script
      run: python scraper.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "Lucas Mori"
        git config --global user.email "lucaskmori@gmail.com"
        git add .
        git commit -m "Update files" || echo "No changes to commit"
        git push
